# .golangci.yml
version: "2"
run:
  timeout: 3m
  issues-exit-code: 1
  tests: true

linters-settings:

  exhaustive:
    default-signifies-exhaustive: true

  godot:
    period: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    confidence: 0.8
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: true
        
formatters-settings:
  gofumpt:
    extra-rules: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - exhaustive
    - godot

formatters:
  enable:
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck