name: Lint Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12